project:
  type: website
  output-dir: docs

website:
  title: "How To Make Your Guide"
  navbar:
    left:
      - href: HowToMakeYourGuide_Span.qmd
        text: Span
      - href: HowToMakeYourGuide_Eng.qmd
        text: Eng
      

format:
  html:
    theme: cosmo
    toc: true
    css: styles/srk.css