project:
  type: website

website:
  title: "How To Make Your Guide"
  navbar:
    left:
      - href: HowToMakeYourGuide_Eng.qmd
        text: Eng
      - href: HowToMakeYourGuide_Span.qmd
        text: Span

format:
  html:
    theme: cosmo
    toc: true
    css: styles/srk.css